name: Deploy to production

on:
  pull_request_labeled:
    - bug

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint

  get_ios_build:
    name: Check for existing iOS production build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: production

  get_ios_staging_build:
    name: Check for existing iOS staging build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: staging

  build_ios_staging:
    name: Build iOS staging
    needs: [get_ios_staging_build]
    if: ${{ !needs.get_ios_staging_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: staging

  submit_ios_staging_build:
    name: Submit iOS staging build
    needs: [build_ios_staging]
    type: submit
    params:
      build_id: ${{ needs.build_ios_staging.outputs.build_id }}

  publish_ios_update:
    name: Publish iOS production update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: update
    params:
      branch: production
      platform: ios

  publish_ios_staging_update:
    name: Publish iOS staging update
    needs: [get_ios_staging_build]
    if: ${{ needs.get_ios_staging_build.outputs.build_id }}
    type: update
    params:
      branch: staging
      platform: ios
